name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'x'

    - name: Run tests
      run: |
        python -m unittest discover -v -p unit_tests.py -s LAB_5